---
title: "ChessM_HTSReadProcessing"
author: "Brandon D. Hoenig"
date: '2022-07-09'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(dada2)
library(seqinr)
```

Read in sequences and create list of sample names
```{r}
fnFs <- sort(list.files(pattern= "_R1_001.fastq"))
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
```

Inspect Quality Plots
```{r}
plotQualityProfile(fnFs[1:2])
```

Place filtered files in filtered/ subdirectory
```{r}
filtFs <- file.path("filtered", paste0(sample.names, "_F_filt.fastq.gz"))
names(filtFs) <- sample.names
```

filter reads
```{r}
out <- filterAndTrim(fnFs, # input
                     filtFs, #output
                     rm.phix = T, #remove PhiX reads
                     compress = T, 
                     multithread = T,
                     trimLeft = 28,
                     trimRight = 26)
head(out)
```

Learn Error Rates 
```{r}
errF <- learnErrors(filtFs, multithread=TRUE)
```

Plot Error Rates
```{r}
plotErrors(errF, nominalQ=TRUE)
```

Sample Inference
```{r}
dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
dadaFs
```

Construct Sequence Table
```{r}
seqtab <- makeSequenceTable(dadaFs)
dim(seqtab)
```

Remove Chimeras
```{r}
seqtab.nochim <- removeBimeraDenovo(seqtab, method="per-sample", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)
```

```{r}
seqtab.nochim %>% 
  colnames()

write.fasta(sequences = as.list(seqtab.nochim %>% 
              colnames()), 
            names = paste0("seq_", c(1:131)),
  as.string = T, file.out = 'output/dada2_processed_sequences.fasta')
```

sequences were then uploaded to BLASTn and downloaded into the 'fromBLASTn' folder
```{r}
seqsFromBLAST <-
read_csv('fromBLASTn/CM61T4MD013-Alignment-HitTable.csv',col_names = F) %>%
  select(X1, X2, X3, X4, X8, X11, X12)

colnames(seqsFromBLAST) <- c("Seq_ID", "Accession", "Perc_Ident", "Match_Len", "Query_Len", "E_Val", "BitScore")
```

```{r}
seqsFromBLAST %>%
  filter(Query_Len > 194) %>%
  mutate(Perc_Len = Match_Len / Query_Len) %>%
  filter(Perc_Len > 0.95) %>%
  filter(Perc_Ident > 95) %>%
  group_by(Seq_ID)  %>% 
  top_n(n=1, wt = BitScore) %>% 
  ungroup() %>%
  select(Accession) %>%
  unique()
```

